### ISSUE TITLE
"No peer certificate" error

### ISSUE THREAD

**Issue by weind** [schnatterer/nusic#12] opened 2017-03-29 20:25 UTC
nusic worked fine for me for a long time but for several weeks I receive the following error:
```
2017-03-29 05:52:02,247 [Thread-15422] ERROR org.a.g.a.a - Fatal transport error: No peer certificate
2017-03-29 05:52:02,250 [Thread-15422] WARN i.s.n.c.impl.SyncReleasesServiceImpl - Error querying releases for artist AC/DC from the internet. No connection to the internet?
org.a.g.f: No peer certificate
at org.a.g.a.a.a(HttpClientWebServiceWs2.java:322) ~[na:0.0]
at org.a.g.a.a.a(HttpClientWebServiceWs2.java:185) ~[na:0.0]
at org.a.g.b.a(DefaultWebServiceWs2.java:207) ~[na:0.0]
at org.a.e.a.a(QueryWs2.java:75) ~[na:0.0]
at org.a.e.a.b.a(SearchWs2.java:70) ~[na:0.0]
at org.a.e.a.a.i(ReleaseSearchWs2.java:74) ~[na:0.0]
at org.a.e.a.a.h(ReleaseSearchWs2.java:64) ~[na:0.0]
at org.a.e.a.a.c(ReleaseSearchWs2.java:44) ~[na:0.0]
at org.a.e.a.a.b(ReleaseSearchWs2.java:38) ~[na:0.0]
at org.a.a.b.i(Release.java:79) ~[na:0.0]
at info.schnatterer.nusic.core.impl.RemoteMusicDatabaseServiceMusicBrainz.findReleases(RemoteMusicDatabaseServiceMusicBrainz.java:152) ~[na:0.0]
at info.schnatterer.nusic.core.impl.SyncReleasesServiceImpl.processArtist(SyncReleasesServiceImpl.java:135) ~[na:0.0]
at info.schnatterer.nusic.core.impl.SyncReleasesServiceImpl.refreshReleases(SyncReleasesServiceImpl.java:104) ~[na:0.0]
at info.schnatterer.nusic.core.impl.SyncReleasesServiceImpl.syncReleases(SyncReleasesServiceImpl.java:77) ~[na:0.0]
at info.schnatterer.nusic.android.service.LoadNewReleasesService$WorkerThread.run(LoadNewReleasesService.java:214) ~[na:0.0]
at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
Caused by: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
at com.android.org.conscrypt.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:146) ~[na:0.0]
at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:93) ~[na:0.0]
at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:388) ~[na:0.0]
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:165) ~[na:0.0]
at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164) ~[na:0.0]
at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119) ~[na:0.0]
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360) ~[na:0.0]
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555) ~[na:0.0]
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487) ~[na:0.0]
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465) ~[na:0.0]
at org.a.g.a.a.a(HttpClientWebServiceWs2.java:256) ~[na:0.0]
... 15 common frames omitted

```

Any idea what might be the cause of this issue? I am using version 3.2.0 on an Android 4.4.4 device.

**Comment by schnatterer** [comment] 2017-03-30 06:44
Hi @weind,

thanks for including the log file, that's really helpful.

How does this error manifest? Is the update failing for all artists or only for some of them?

I've witnessed MusicBrainz beeing not very reliable for some time. That is, maybe 1/100 requests are failing with all kinds of errors (sometimes [rate limiting](https://musicbrainz.org/doc/XML_Web_Service/Rate_Limiting), timeouts, etc.). Haven't seen `No peer certificate`, though. MusicBrainz' certificate hasn't changes since september...Maybe it's an android 4 related issue.

I added a feature to v.3.2.0 which notifies you about how many of the requests failed. You can enable it in the `Settings` | `Developer Settings` | `Show Errors during refresh`.
In addition a summary of the exceptions is logged. Maybe you can post it here. It looks like this:

`3 different exceptions while loading releases: [org.a.g.f: Unable to resolve host "musicbrainz.org": No address associated with hostname, org.a.g.f: Connection to https://musicbrainz.org refused, org.a.g.f: Connect to /138.201.227.205:443 timed out]`

**Comment by weind** [comment] 2017-03-30 07:23
It always happens for all artists:
`2017-03-30 09:15:09,619 [Thread-1251] INFO i.s.nusic.android.util.Notification - Notifcation: Update der Alben für 96 Interpreten von 96 fehlgeschlagennull
2017-03-30 09:15:09,634 [Thread-1251] WARN i.s.n.a.s.LoadNewReleasesService - Loading releases finished with errors for 96/96 artists
2017-03-30 09:15:09,636 [Thread-1251] WARN i.s.n.a.s.LoadNewReleasesService - 1 different exceptions while loading releases: [org.a.g.f: No peer certificate]
2017-03-30 09:15:09,641 [main] INFO i.s.nusic.android.util.Toast - Toast: Update der Alben für 96 Interpreten von 96 fehlgeschlagen
2017-03-30 09:16:06,885 [main] WARN i.s.n.a.LoadNewRelasesServiceBinding - Service unexpectedly not bound, assuming it's not running`

**Comment by schnatterer** [comment] 2017-03-31 20:36
I could reproduce the error on Android 5. I does not occurr on Android >= 6

After doing a bit of research I suspect the following:

* MusicBrainz must have changed their infrastructure, which now relies on [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication). Why do I think so?  
`openssl s_client -tls1 -connect musicbrainz.org:443` returns a self signed certifacte, but 
`openssl s_client -tls1 -servername musicbrainz.org -connect musicbrainz.org:443` returns the "proper" certificate, also returned when going to musicbrainz.org in a modern browser.
* The library used by nusic to get data from MusicBrainz, [musicbrainzws2-java](https://github.com/schnatterer/musicbrainzws2-java) (I only forked it, I don't really maintain it) uses Apache HTTP client
* Android contained an old version of Apache HTTP client, which [does not support SNI](http://stackoverflow.com/a/5895320/1845976), which [was removed in Android 6.0](https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client).
* So, when running on Android< 6, nusic must use Android's Apache HTTP client, which results in the error. On Android 6 and above, nusic can use the Apache HTTP client shipped by musicbrainzws2-java, which supports SNI. No error.  

That's a tough one!
I already tried updating musicbrainzws2-java's Apache HTTP client (1886be5), but (as suspected above) no luck.

 What options do we have?

* Create an android specific version of musicbrainzws2-java, that uses android's HTTP Client or refactor it to use java.net.URLConnection
* Adapt musicbrainzws2-java to use a shadowed version of HTTP client
* Adapt musicbrainzws2-java to provide the option of using HTTP instead of HTTPS and then tell nusic to use HTTP on Android < 6.
* Maybe some other options?

Unfortunately, none of these are a quick fixes and in addition I'm (almost) off to four weeks of holidays.

I'll look into it once I'm back. 😐

**Comment by schnatterer** [comment] 2017-04-01 07:38
I tried a shading Apache HTTP client. This results in a different exception. Probably the same cause, though.
Android's SSL/TLS implementation in `com.android.org.conscrypt` is just not accepting the certificate...
I'll try to contact MusicBrainz. Maybe they can do something about it.
```
org.musicbrainz.g.f: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at org.musicbrainz.g.a.a.a(HttpClientWebServiceWs2.java:295) ~[na:0.0]
	at org.musicbrainz.g.a.a.a(HttpClientWebServiceWs2.java:162) ~[na:0.0]
	at org.musicbrainz.g.b.a(DefaultWebServiceWs2.java:203) ~[na:0.0]
	at org.musicbrainz.e.a.a(QueryWs2.java:74) ~[na:0.0]
	at org.musicbrainz.e.a.b.a(SearchWs2.java:70) ~[na:0.0]
	at org.musicbrainz.e.a.a.i(ReleaseSearchWs2.java:74) ~[na:0.0]
	at org.musicbrainz.e.a.a.h(ReleaseSearchWs2.java:64) ~[na:0.0]
	at org.musicbrainz.e.a.a.c(ReleaseSearchWs2.java:44) ~[na:0.0]
	at org.musicbrainz.e.a.a.b(ReleaseSearchWs2.java:38) ~[na:0.0]
	at org.musicbrainz.a.b.i(Release.java:79) ~[na:0.0]
	at info.schnatterer.nusic.core.impl.RemoteMusicDatabaseServiceMusicBrainz.findReleases(RemoteMusicDatabaseServiceMusicBrainz.java:152) ~[na:0.0]
	at info.schnatterer.nusic.core.impl.SyncReleasesServiceImpl.processArtist(SyncReleasesServiceImpl.java:135) ~[na:0.0]
	at info.schnatterer.nusic.core.impl.SyncReleasesServiceImpl.refreshReleases(SyncReleasesServiceImpl.java:104) ~[na:0.0]
	at info.schnatterer.nusic.core.impl.SyncReleasesServiceImpl.syncReleases(SyncReleasesServiceImpl.java:77) ~[na:0.0]
	at info.schnatterer.nusic.android.service.LoadNewReleasesService$WorkerThread.run(LoadNewReleasesService.java:214) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:306) ~[na:0.0]
	at org.musicbrainz.org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396) ~[na:0.0]
	at org.musicbrainz.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355) ~[na:0.0]
	at org.musicbrainz.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[na:0.0]
	at org.musicbrainz.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[na:0.0]
	at org.musicbrainz.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[na:0.0]
	at org.musicbrainz.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[na:0.0]
	at org.musicbrainz.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[na:0.0]
	at org.musicbrainz.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[na:0.0]
	at org.musicbrainz.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[na:0.0]
	at org.musicbrainz.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[na:0.0]
	at org.musicbrainz.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[na:0.0]
	at org.musicbrainz.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[na:0.0]
	at org.musicbrainz.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[na:0.0]
	at org.musicbrainz.g.a.a.a(HttpClientWebServiceWs2.java:229) ~[na:0.0]
	... 15 common frames omitted
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318) ~[na:0.0]
	at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219) ~[na:0.0]
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:113) ~[na:0.0]
	at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:525) ~[na:0.0]
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) ~[na:0.0]
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:302) ~[na:0.0]
	... 29 common frames omitted
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	... 35 common frames omitted
```

**Comment by schnatterer** [comment] 2017-04-01 14:57
Created a bug at MusicBrainz ([MBH-481](https://tickets.metabrainz.org/browse/MBH-481)), maybe they can solve it server side.

**Comment by schnatterer** [comment] 2017-04-02 20:28
@weind, there's news.
[MusicBrainz changed their server config](https://tickets.metabrainz.org/browse/MBH-481?focusedCommentId=42980&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-42980). Nusic now works again on my android 5 test device that didn't work before.

How about you on android 4.4.4.4?

**Comment by zas** [comment] 2017-04-02 20:36
> Created a bug at MusicBrainz (MBH-481), maybe they can solve it server side.

You're right, we move to SNI, as a result of our infrastructure change in last november.
Of course, if possible, try to use libraries supporting SNI.

That said, I changed the default cert to be the one used by the web service. I'm not really happy with this hacky move, but it should solve your issue without too much negative impact (i may revert this change if i get negative reports). In this case, i'm thinking about another solution, but it will require changes i would prefer to avoid.

**Comment by weind** [comment] 2017-04-02 21:11
It works for me, too! Thank you very much for your quick help @schnatterer and @zas! And happy holidays for you @schnatterer.

**Comment by schnatterer** [comment] 2017-04-02 21:43
That sounds great! Many thanks to @zas. I hope you don't have to revert your changes ;-)

Thanks @weind for reporting. Unfortunately, I didn't notice the bug myself. Didn't have too much time for nusic recently.

Closing the issue just in time, I'm off in 5 hours :-)

**Closed by schnatterer** 2017-04-02 21:43 UTC
